spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/smallShop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: 12345678901234567890123456789012



